apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
secretGenerator:
- name: haneepass
  literals:
  - password=haneeroot
resources:
  - deployment-mysql.yaml
  - deployment-joomla.yaml

